### ISSUE TITLE
gyp ERR! stack Error: EACCES: permission denied, mkdir '/data/mynode/node_modules/bufferutil/build'  

### ISSUE THREAD

**Issue by spursy** [bitpay/bitcore#1790]
process **bitcore create mynode,**  System throw the followed exception.

```
 amazon-ebs:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    amazon-ebs:                                  Dload  Upload   Total   Spent    Left  Speed
    amazon-ebs: 100   619    0   619    0     0    832      0 --:--:-- --:--:-- --:--:--   833
    amazon-ebs: 100 24.6M  100 24.6M    0     0  4547k      0  0:00:05  0:00:05 --:--:-- 5438k
    amazon-ebs:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    amazon-ebs:                                  Dload  Upload   Total   Spent    Left  Speed
    amazon-ebs: 100   604    0   604    0     0    875      0 --:--:-- --:--:-- --:--:--   875
    amazon-ebs: 100  1154  100  1154    0     0    687      0  0:00:01  0:00:01 --:--:--  4387
    amazon-ebs: Unpacking bitcoin distribution
    amazon-ebs: bitcoin-0.12.1/
    amazon-ebs: bitcoin-0.12.1/bin/
    amazon-ebs: bitcoin-0.12.1/bin/bitcoin-cli
    amazon-ebs: bitcoin-0.12.1/bin/bitcoind
    amazon-ebs: bitcoin-0.12.1/bin/bitcoin-qt
    amazon-ebs: bitcoin-0.12.1/bin/bitcoin-tx
    amazon-ebs: bitcoin-0.12.1/bin/test_bitcoin
    amazon-ebs: bitcoin-0.12.1/bin/wallet-utility
    amazon-ebs: bitcoin-0.12.1/include/
    amazon-ebs: bitcoin-0.12.1/include/bitcoinconsensus.h
    amazon-ebs: bitcoin-0.12.1/lib/
    amazon-ebs: bitcoin-0.12.1/lib/libbitcoinconsensus.so
    amazon-ebs: bitcoin-0.12.1/lib/libbitcoinconsensus.so.0
    amazon-ebs: bitcoin-0.12.1/lib/libbitcoinconsensus.so.0.0.0
    amazon-ebs:
    amazon-ebs: > bufferutil@1.2.1 install /data/mynode/node_modules/bufferutil
    amazon-ebs: > node-gyp rebuild
    amazon-ebs:
    amazon-ebs: gyp ERR! configure error
    amazon-ebs: gyp ERR! stack Error: EACCES: permission denied, mkdir '/data/mynode/node_modules/bufferutil/build'
    amazon-ebs: gyp ERR! System Linux 4.4.0-1072-aws
    amazon-ebs: gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
```
