### ISSUE TITLE
docker-compose cannot find .env folder

### ISSUE THREAD

**Issue by fraballi** [bitpay/bitcore#3341]
Cannot find .env folder, when running `docker-compose`:
___/bitcore-8.25.25/.env___

So this is the `docker-compose.yml` script portion calling it:

```yaml
# ...
  bitcore-node:
    build: .
    image: bitcore-node
    links:
      - database
    ports:
      - 8100:8100
      - 3000:3000
    environment:
      - DB_HOST=database
    env_file: .env    # this section
``` 

In order this can run correctly, what credentials, properties, etc. should be included and in what file format?
